#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 03 18:15:17 IST 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim lab3_wallance_tb_behav -key {Behavioral:sim_1:Functional:lab3_wallance_tb} -tclbatch lab3_wallance_tb.tcl -view /home/u24ev057/hdl_cao/CAO_lab/vivado_proj/cao_lab_u24ev057/lab3_wallance_tb_behav.wcfg -log simulate.log"
xsim lab3_wallance_tb_behav -key {Behavioral:sim_1:Functional:lab3_wallance_tb} -tclbatch lab3_wallance_tb.tcl -view /home/u24ev057/hdl_cao/CAO_lab/vivado_proj/cao_lab_u24ev057/lab3_wallance_tb_behav.wcfg -log simulate.log

